name: Reusable Workflow Example

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: RascalTwo/TestRepoPleaseIgnore/.github/workflows/reusable-workflow.yml
    with:
      message: "Hello, World!"